a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético?' ,a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Esta em maiúsculas? ', a.isupper())
print('Esta em minúsculas? ', a.islower())
print('Esta capitalizada? ', a.istitle())

#a = input('Digite algo: ')
#print(f'O tipo primitivo desse valor é {type(a)} ')
#print(f'Só tem espaços? {a.isspace()}')
#print(f'É um número? {a.isnumeric()}')
#print(f'É alfabético? {a.isalpha()}')
#print(f'É alfanumérico? {a.isalnum()}')
#print(f'Esta em maiúsculas? {a.isupper()}')
#print(f'Esta em minúsculas? {a.islower()}')
#print(f'Esta capitalizada? {a.istitle()}')