tabela = ('Corinthians', 'Palmeiras', 'Santos', 'Gremio', 'Cruzeiro', 'Flamengo', 'Vasco da Gama', 'Chapecoense', 'Atlético Mineiro', 'Botafogo', 'Atlético-pr', 'Bahia', 'Sao Paulo', 'Fluminense', 'Sport Recife', 'EC Vitoria', 'Curitiba', 'Avai', 'Ponte Preta', 'Atlético-go')
print('=' * 20)
print(f'Lista de times do Brasileirão: {tabela}')
print('=' * 20)
print(f'Os 5 primeiros são {tabela[0:5]}')
print('=' * 20)
print(f'Os 4 Últimos são {tabela[16:21]}')
print('=' * 20)
print(f'Times em Ordem Alfabética: {sorted(tabela)}')
print('=' * 20)
print(f'O Chapecoense está na {tabela.index("Chapecoense")+1} posição')
